### ISSUE TITLE
XamarinStudio support

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/Cognitive-LUIS-Windows#12]
I have tried to run the project in `Sample/` in Xamarin, but it seems that this project is VisualStudio only. Is it possibile to add a Xamarin iOS/Droid or just a SharedLibrary example? It would make a lot of sense as for the new .NET standard library xamarin integration!

Thank you

**Comment by Ahmkel** [comment]
Unfortunately, this is not currently in our plans. 
We will update you if we add it to the plans in the future.
Thanks.

**Comment by loretoparisi** [comment]
@Ahmkel by the way what I'm doing right now is to use Cognitive `LUIS` via node `Botframework` sdk, and to test it, since we mostly use `macOS` to developer, I'm using `BFEmulator.exe` via `mono` - see https://github.com/Microsoft/BotBuilder/issues/558

So at the end I access `LUIS` in this way :)
