### ISSUE TITLE
Max number of utterances per LUIS app/intent

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/Cognitive-LUIS-Windows#17]
Hi there, 

We're in the process of developing a bot for the Fintech sector. We're using LUIS and the MS Bot framework. A question we have at the moment is - is there a maximum number of utterances that LUIS can handle per app/per intent? We'd like to train our models very thoroughly, well, in the range of a thousand or so utterances per intent at the moment & we are concerned that we might overload things/degrade the performance. 

Any advice would be much appreciated.

**Comment by pushsos** [comment]
i found out to be 1000 is the max limit
