### ISSUE TITLE
SampleUserControlLibrary project missing

### ISSUE THREAD

**Issue by PrasadHonrao** [Microsoft/Cognitive-LUIS-Windows#2]
LUISAPI-WPF-Samples solution has a reference to SampleUserControlLibrary project, which is not available in the current code base.

**Comment by ManishChitre** [comment]
Yes, LUISAPI-WPF-Samples solution has a reference to SampleUserControlLibrary project and is missing.

**Comment by heshamelbaz** [comment]
Will check the reference as soon as possible, thank you.

**Comment by heshamelbaz** [comment]
Sorry for not including this in the readme file, but the project depends on a submodule, so in order to clone the repository with the submodules you'll have to use:
`git clone --recursive  https://github.com/Microsoft/Cognitive-LUIS-Windows.git`

Will update the readme file accordingly.
