### ISSUE TITLE
MS LUIS.ai | Our app stopped returning matches for some entities

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/Cognitive-LUIS-Windows#20]
So we have a luis app with the intent RequestFundFact, and we have the hierarchical entities Fund and FundFact used in several utterances mapped to this intent. 

Our calls to the endpoint were returning correct results for queries such as "give me the investor profile for the managed fund", which return something like: 

RequestFundFact/0.9936668. Entities: Fund, managed fund; FundFact: investor profile 

However, as of this afternoon our endpoint for RequestFundFact is no longer returning the Fund entity, for the exact same data. 

In fact none of the utterances mapped to that intent are returning the Fund entity. The FundFact entity still returns however. 

We have done some additional training today, but surely that shouldn't cause the whole thing to have fallen over? 

Any help much appreciated.

**Comment by MahadevanAlagar** [comment]
Team,

Experiencing the same issue, in our app as well. The exact same text as is in the indent's utterances are not returning the same intent, instead resulted to another intents, even after multiple training and publish also. 

How to make sure the prediction is more accurate?
Any insights to improve the accuracy will be much helpful.
