### ISSUE TITLE
LUIS returns 401 Unauthorised with Azure portal generated subscription key

### ISSUE THREAD

**Issue by Kothakapu** [Microsoft/Cognitive-LUIS-Windows#23]
Hi Team,

I'm getting 401 (Access denied due to invalid subscription key) error when I'm trying to access LUIS Programmatic API. I'm testing this in Luis API console.

Please help me out on this.

**Comment by xitij** [comment]
Bump. I'm seeing this as well. I've tested using Postman as well as the provided "testing api portal" both requests are identical, both fail with the same response.
```
apim-request-id: 92887904-db4c-48c0-bd63-39c4a8b144b0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Date: Wed, 29 Mar 2017 03:41:36 GMT
WWW-Authenticate: AzureApiManagementKey realm="https://westus.api.cognitive.microsoft.com/luis/api/v2.0",name="Ocp-Apim-Subscription-Key",type="header"
Content-Length: 143
Content-Type: application/json

{
  "statusCode": 401,
  "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."
}
```

**Comment by xitij** [comment]
@Kothakapu I managed to resolve this issue finally. This SO [post](http://stackoverflow.com/questions/41603082/401-errors-calling-the-microsoft-luis-ai-programmatic-api) was helpful.
1) Go to www.luis.ai, and sign in.
2) Once signed in, click on the "My Keys" tab (right next to My Apps)
3) Use that key.

Hope that helps...

**Comment by felixhao28** [comment]
@xitij Hi, I am also running into this problem. And I wonder what key did you use in "My Keys" tab? I tried both key1 and key2 in my Azure portal but none of them works.

**Comment by xitij** [comment]
@felixhao28 Don't go to the Azure portal, go to the page I linked above.
1. Go to https://www.luis.ai/home/keys
2. Sign in
3. Use the key from the "Endpoint Keys" page.

**Comment by felixhao28** [comment]
@xitij But there is only a "BootstrapKey" available and message shows it will expire in 30 days.

**Comment by xitij** [comment]
@felixhao28 Yeah there should be a "Programmatic API Key" there. That's the one you're looking for. I think you'll need to generate, or buy one then. I'm not actually sure how that's done.

**Comment by guendas** [comment]
Did you try a key generated by the Azure Portal? 
(Going to Azure Portal -> new service -> Cognitive Services -> LUIS)

**Comment by felixhao28** [comment]
Somehow it works now but not a week ago. I guess it probably needs some time for the key from Azure to propagate to LUIS portal. Thanks.

**Comment by MahadevanAlagar** [comment]
Team,

Azure Subscription Keys are returning 401 error, but can use the LUIS Programmatic API Key, which works, but the access are limited. In order to higher number of request, using the Azure Subscription Keys will allow to change the pricing tier, for more number of requests, if required.

**Comment by sanjaydebnath** [comment]
Just make sure your domain is actually correct in your LuisModel Attribute. I faced the same issue and after some r&d found that Luis by default takes west US as domain if you don't provide the same. So make sure the domain is correct...

```
if (domain == null)
        domain = apiVersion == LuisApiVersion.V2 ? "westus.api.cognitive.microsoft.com" : "api.projectoxford.ai/luis/v1/application";
```

So if your service is hosted somewhere else make sure domain is correctly specified...

`[LuisModel("***", "***", domain: "eastus2.api.cognitive.microsoft.com")]`
Note I'm using V2 API.

**Comment by sanjaydebnath** [comment]
Just make sure your domain is actually correct in your LuisModel Attribute. I faced the same issue and after some r&d found that Luis by default takes west US as domain if you don't provide the same. So make sure the domain is correct...

```
if (domain == null)
        domain = apiVersion == LuisApiVersion.V2 ? "westus.api.cognitive.microsoft.com" : "api.projectoxford.ai/luis/v1/application";
```
So if your service is hosted somewhere else make sure domain is correctly specified...

```
[LuisModel("***", "***", domain: "eastus2.api.cognitive.microsoft.com")]
Note I'm using V2 API.
```

**Comment by kwill-MSFT** [comment]
See https://blogs.msdn.microsoft.com/kwill/2017/05/17/http-401-access-denied-when-calling-azure-cognitive-services-apis/ for all of the common causes and solutions for 401 Access Denied in Cognitive Services.

**Comment by weerdm** [comment]
Same issue.. Used an Azure key, the correct region and waited for 30 min. Still saying the key is invalid.

**Comment by v-geberr** [comment]
@weerdm Did you assign the new key from azure in your app's publish page?

**Comment by Lorempn2** [comment]
Turns out i had to use the programmatic keys when managing the apps. When quering, you need to use the Azure key.

**Comment by benc-uk** [comment]
I'm getting a 401 when I use any key generated from Azure. I've added the key to my app in eu.luis.ai portal, it's there in the list. When I use that key in [REST API](https://westeurope.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff) it never works, always returns 401.

If I try the starter key, then it is fine.
This has to be a bug

**Comment by v-geberr** [comment]
Hi @benc-uk, Can you tell me your path through the documentation? Where you started and where you went back to when you were blocked with the keys? Thx, Dina

**Comment by qs-wang** [comment]
Same issue.  I try to make it clear here
1. Call the api to provision the apps, etc.  I have to use the programming key.  For example the 

 {"method":"POST","uri":"https://australiaeast.api.cognitive.microsoft.com/luis/api/v2.0/apps/{appid}/versions/0.1/customprebuiltdomains","versionId":"0.1","headers":{"subscription-key":"whatever"},"body":{"domainName":"Camera"}}
However this is key has the limitation, so if I call the app parallel, I got . { " error":{ "statusCode": 429, "message": "Rate limit is exceeded. Try again in 1 second." } }" .

2. Call the api to query the end point. I think the azure keys are ok, though I haven't really push to the limit yet.

**Comment by Lorempn2** [comment]
Yes, this is poorly documentented. Took me some hours and a support ticket to figure it all out. In summary you have to use the programmatic api to manage the app and the Azure key to query the app. 

To me it is still not clear what the limits of the programmatic key are. The docs are stating something like 1.000.000 a month but apparently there is also some undocumented rate limiting going on..

**Comment by v-geberr** [comment]
This [doc page ](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/manage-keys) might help with the difference between authoring and endpoints. This [doc page](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-boundaries#key-limits) explains the key limits.

**Comment by Lorempn2** [comment]
Is does not explain the rate limit of the starter/authoring key

**Comment by v-geberr** [comment]
It is 5 requests per second.

**Comment by videepthMSFT** [comment]
@v-geberr  is there no exhaust limit for this starter key when I use it for rest api calls using the rest api portal or postman?

**Comment by isathish** [comment]
404
We're sorry! The page you are looking for can not be found. That means we either broke something or the page you requested does not exist.
