### ISSUE TITLE
Missing SampleUserControlLibrary in the sample Solution

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/Cognitive-LUIS-Windows#25]
I get a load failed for the referenced library meaning the sample cannot be run out of the box and cannot find any files that might correspond in the respository. Was this missed from the Git commit?

To replicate, clone the project into a fresh directory and try to open and run the sample app.

**Comment by cthrash** [comment]
Please take a look at https://github.com/Microsoft/Cognitive-LUIS-Windows/issues/2.

**Comment by brendanarnold** [comment]
Ah ok - thanks, I missed that
