### ISSUE TITLE
Guidance on parsing the resolution of the builtin.datetime.duration entity

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/Cognitive-LUIS-Windows#27]
I get an entity of type `builtin.datetime.duration` returned corresponding to 'last week'. This is resolved to 'P1W' which I assume means 'past one week' however I don't know for sure and I can't seem to find docs detailing what other values are possible.

Is there existing code to parse this into usable .NET `DateTime` objects? Or a guide on how to interpret the returned strings?

**Comment by tellarin** [comment]
DateTimeV2 includes resolutions.
@stevengum97, can we close this issue?
