### ISSUE TITLE
How Can I Enable This SDK!

### ISSUE THREAD

**Issue by iamanas20** [Microsoft/Cognitive-LUIS-Windows#34]
Hi, how exactly can I make this work in Visual Studio 2017?

**Comment by tsahi** [comment]
get it as a [package from nuget](https://www.nuget.org/packages/Microsoft.Cognitive.LUIS/), and use the API.

**Comment by stevengum97** [comment]
Since a valid answer was provided, I'm closing this issue. If you have any questions please feel free to @-mention me directly.
