### ISSUE TITLE
[LUIS] Can't add phrase list to my app

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/Cognitive-LUIS-Windows#35]
I can't add phrase list to my app. The save button is not highlighting, although I am separating the entities by commas. [screenshot](https://postimg.org/image/xhabu58tn/)

What is the required field 'APP.FEATURE.PHRASELIST.MODAL.ADD.LABEL'?

**Comment by sdharshraj** [comment]
Same here i am also not able to update phrase list

**Comment by mahmoudahmedarafa** [comment]
@sdharshraj You can do a hard refresh in your browser (CTRL + F5) and it will work fine.

**Comment by maxxx580** [comment]
when I hard refresh, it actually check sign-in status and redirect to luis homepage. still not be able to add more phrase list, though I have added the one in tutorial.

**Comment by ellwoods** [comment]
I get the same, I've tried different browsers too, CTRL + F5 achieves nothing for me in Chrome or IE

**Comment by maxxx580** [comment]
@ellwoods I get this figured out. You need to have your mouse focus somewhere else and they will should up in the suggested field, though I forget exactly where.  It's a pretty tricky thing.

**Comment by premchandpl** [comment]
@maxxx580 I am having the same issue. I am not able to add phrase list. The save button id disabled. I tried in all 3 browsers and in all 3 browsers, the save button is disabled.

I cleared my cache, done ctrl+f5 and still the same issue. Let me know if there is any solution to this?

**Comment by SibaprasadM** [comment]
After putting necessary entries in 'Value (Required) ' Field, you need to hit Enter . This will enable Save , Add all and Recommend buttons.
