### ISSUE TITLE
Where is this SDK going?

### ISSUE THREAD

**Issue by tsahi** [Microsoft/Cognitive-LUIS-Windows#36]
This repository hasn't seen a commit in 8 months, while the LUIS service is moving forward. The API hardly covers a tiny bit of the features available from the LUIS web service. Should we expect this SDK to be developed, or should we make direct calls to the web service instead?

**Comment by stevengum97** [comment]
@tsahi, sorry for the delay in our response! Right now the new Runtime (Prediction, like this SDK) and Programmatic (Authoring) SDKs are [pending](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Language/LUIS) a NuGet release from the Azure SDK for .NET team. After those are released we'll be redirecting from this repository to [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) and asking users to leave feedback for the SDK on that repository. 

I'm going to close this issue for now, but if you have any questions feel free to reopen it and @-mention me directly.

**Comment by tsahi** [comment]
@stevengum97 , does that mean this SDK is essentially deprecated, and we'll have to move to the Azure SDK for .NET?

LIke many, I'm using LUIS in a bot I'm working on. If I move my implementation to the MS Bot Framework, is this something I have to consider, or is there a built-in access to LUIS in Bot Framework?
