### ISSUE TITLE
DateTimeV2 support

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/Cognitive-LUIS-Windows#37]
It seems that DateTimeV2 is not available in pt-br although it says [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/pre-builtentities ) that it is supported.

Any plans on this?

**Comment by stevengum97** [comment]
The current timeframe for datetimeV2 support for pt-br are by the time LUIS reaches GA.

**Comment by esalcedoo** [comment]
Hi! As far as i know LUIS have officially gone GA. Is there any updates on this topic?

**Comment by tellarin** [comment]
Hi @esalcedoo, PT-BR is now fully supported in DateTime since last December.
This issue was tracked in the Recognizers-Text repo (https://github.com/Microsoft/Recognizers-Text/issues/11).

If you find any issues, please report them there. Thanks!

**Comment by tellarin** [comment]
@stevengum97, we can close this one.
