### ISSUE TITLE
[LUIS] Offline testing gives different results from endpoint url testing

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/Cognitive-LUIS-Windows#41]
Here is my endpoint url testing result:

![endpoint testing](https://user-images.githubusercontent.com/22199398/27079639-bae13300-5038-11e7-97e4-6d25f91ec640.PNG)

And here is my offline testing result:

![offline testing](https://user-images.githubusercontent.com/22199398/27079684-ef9191e4-5038-11e7-9a98-e735175473cf.PNG)

They both test with the same sentence, so how could they produce different results (5 entities vs 3)?

**Comment by vijaysaimutyala** [comment]
@mahmoudahmedarafa Were you able to find out the reason and possible solution for this?
