### ISSUE TITLE
Training and publishing applications

### ISSUE THREAD

**Issue by allantargino** [Microsoft/Cognitive-LUIS-Windows#46]
The SDK doesn't implement application's training and publishing. Here are the service endpoints:

- Train a model: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c45
- Get training status: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c46
- Assign a key to an app: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c42
- Publish an app: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c3b

**Comment by fanidamj** [comment]
May I know if you still have this issue?

**Comment by allantargino** [comment]
Hey @fanidamj . I opened this issue in order to report some gaps on LUIS SDK.
I've already sent a Pull Request addressing that (#53)
