### ISSUE TITLE
Unable to add Bing Spell Check

### ISSUE THREAD

**Issue by DanHibbert** [Microsoft/Cognitive-LUIS-Windows#51]
When trying to add the bing spell check, the key value field is a dropdown so am unable to paste the azure key in.  This is for a bot created in eu.luis.ai.
Thanks in advance for helping 

![luis_bing](https://user-images.githubusercontent.com/1837710/28139624-dced1ace-674c-11e7-81e3-fd723ef3f4b3.PNG)

**Comment by rawatsudhir** [comment]
Same...Neither I able to select nor type in
![bingluis](https://user-images.githubusercontent.com/6231820/29548753-f6b6d082-8720-11e7-9dd7-e474d2fc63d3.png)

**Comment by rawatsudhir** [comment]
Okay..got it working. One needs to add keys in MyKeys from the App and then use it while publishing the app. Refer below image
![correct1](https://user-images.githubusercontent.com/6231820/29549084-96281fac-8723-11e7-9991-e7024c40f4e4.png)

![correct2](https://user-images.githubusercontent.com/6231820/29549088-9d65387c-8723-11e7-98a0-610c88c063ee.png)

**Comment by bergmeister** [comment]
Still not working since I cannot edit the key to insert the bing key in the endpoint uri.
