### ISSUE TITLE
No en-gb culture. Particularly problematic with DateTimeV2 

### ISSUE THREAD

**Issue by tam203** [Microsoft/Cognitive-LUIS-Windows#55]
The lack of en-gb culture means we are using the us culture, however this doesn't work well for dates in the datetimeV2 method.

For example in the uk 01/02/17 would represent 1st of Feb 2017 but LUIS parses as 2nd Jan 2017.

**Comment by tellarin** [comment]
This issue is tracked here: https://github.com/Microsoft/Recognizers-Text/issues/212. Currently under planning.
