### ISSUE TITLE
How to unable Enable bing spell checker in Luis?

### ISSUE THREAD

**Issue by dileepkantapop** [Microsoft/Cognitive-LUIS-Windows#56]
Hi Folks,

I am facing the issue with the spell checker option in LUIS, As i am checked it and published. When i see again its showing as unchecked. I had purchased Bing spell check key too. 

Please help me with this...

Thank you...!!

**Comment by rawatsudhir** [comment]
Check here and I am sure it will help https://github.com/Microsoft/Cognitive-LUIS-Windows/issues/51

**Comment by dileepkantapop** [comment]
@rawatsudhir  i had followed these all steps, but no use...

**Comment by rawatsudhir** [comment]
@dileepkantapop  Got it. Yes, it's switching back to default one. The behavior is same for "Add verbose flag "

Not sure if it's by design.

**Comment by stevengum97** [comment]
@dileepkantapop and @rawatsudhir, this is the current design. As long as you use the endpoint that had the settings you configured (e.g. disabling `spellCheck`, setting `verbose=false`) you will receive the results that match your settings.

**Comment by JPThorne** [comment]
The UI does not persist the setting.
