### ISSUE TITLE
Having Issue in adding the utterances

### ISSUE THREAD

**Issue by Naveen-Yaragall** [Microsoft/Cognitive-LUIS-Windows#57]
![image](https://user-images.githubusercontent.com/31060636/29351367-0f42da60-8280-11e7-99b4-6736246fc900.png)

I'm getting the information message  whenever I add the new utterance and the utterance is not getting added. The message "Predicting utterance" pops up  but the utterance doesn't get added.
If we refresh the page it is directly taking to the sign-in page even though we are signed in.

**Comment by stevengum97** [comment]
Hello @Naveen-Yaragall, this is a known issue that we're working on. In the meantime, if the utterance was not successfully added please attempt to add the utterance after at least 15 minutes.
