### ISSUE TITLE
Not able to configure keys in LUIS

### ISSUE THREAD

**Issue by MadhuAcc12** [Microsoft/Cognitive-LUIS-Windows#60]
How to publish in the new UI of Luis? The tenant id is not getting listed in my account. I have generated keys in the azure portal but not able to configure it in LUIS. Any help on this? 

![image](https://user-images.githubusercontent.com/30169639/31275811-49853b74-aab6-11e7-9c53-b08522b6ef20.png)

**Comment by JPThorne** [comment]
You have to be logged into LUIS with the same account you're using in the Azure Portal. 

But. This is also an issue for us in that our selected settings are not persisted and not always accessible.

**Comment by Leslie-Wong-H** [comment]
The same problem -- no tenant item listed, just blank space. 

![image](https://user-images.githubusercontent.com/27696701/77395428-8207bf80-6ddc-11ea-865f-e8394586d7aa.png)

Signed in with GitHub account linked with Microsoft account, and already created a Language Understanding Authoring (LUIS) service at Azure portal. 

The data at Azure does not sync with the luis.ai side?

Anything that I did wrong? Just followed this tutorial step by step.

https://docs.microsoft.com/en-us/learn/modules/create-and-publish-a-luis-model/5-exercise-train-luis-model
