### ISSUE TITLE
Increasing the predicted intents for syntax words

### ISSUE THREAD

**Issue by mynksthi** [Microsoft/Cognitive-LUIS-Windows#64]
How can i increase the prediction intent for the syntax words like order, ordering ,orders ?
I have tried by defining them , in list entity (synonym)
also i have tried with the add phrase feature
How can increase the prediction for it upto minimum 0.7 ?

Thanks

**Comment by JPThorne** [comment]
In our experience, entities are a decent way, phrase lists too. How much training have you done? i.e. how many utterances do you have mapped to your intents? How many intents do you have?

**Comment by mynksthi** [comment]
Thanks for your reply 
i am on a very initial phase of it utterances defined 14-20
intents 6
entities 8-9

**Comment by JPThorne** [comment]
20 utterances per intent is not too bad; around 50 to 100 is better, so maybe try upping the number of utterances per intent?

also, the similarity of the utterances can bring the score down. i.e. if your utterances all/some have fairly similar structures we found that LUIS get's 'confused' and scores lower. 

we treat a score of below 0.5 as being 'too low' & then handle it in code.

**Comment by mynksthi** [comment]
Where i should define the similiar words 
1. - order , orders , ordering 
or
2. Shipment , supply , export
in utterances ,   features to add phrase or , in entity (list)synonyms
