### ISSUE TITLE
LUIS Result is different in Web UI and Web service call

### ISSUE THREAD

**Issue by gcsonka** [Microsoft/Cognitive-LUIS-Windows#66]
Background:
I have a Bot that is using LUIS calling the API directly with my paid Azure subscription.
I have a number intents with a varying number of utterances (up to 600).

Issue:
I see an issue occasionally when the LUIS Web UI (Test and Intents screen) correctly predict an intent, but my client using the API call incorrectly gets something else. 

When I clicked on the Luis API URL above the publish button in the LUIS web UI and added my sentence to predict, I would get an incorrect answer, yet when I go to the Test and Train or Intents page, it works fine.

Here is what I did so far:

1. I made sure model is trained and published every time
2. Tested the API URL on the Publish page vs Test and Train page - they produce different predictions
3. Tested bot calling API in c#, vs Test and Train page - they produce different predictions
4. I made sure my exact sentence is labeled in the correct intent
5. I made sure my exact sentence is NOT labeled in the INcorrect intent
6. I tested the API URL with my paid subscription key as well as my free programmatic key - both can produce the error

I also have seen this with labeling entities: Web UI Test and Intents screens correctly predict and label  6 entities, where API call only gets 5.

None of this seems to help.  Ended up creating a bunch of UnitTests in my app to see if LUIS still works as it should. About 2-3 out 10 times it fails.

Anyone else seen this issue? Any recommendations?
Thanks in advance.
gabics

**Comment by Kv-wood** [comment]
We are facing similar issues where the Test Console from LUIS Portal is returning the correct Intent+Score for an utterance but the Web API call is returning a different result (via Postman).
We have 2 LUIS Applications (French and Dutch), each with around 90 intents and 700 utterances.
Fortunately we were able to fix it by adding a new utterance to the Intent, train and publish the changes then the results were the same on both sides.
But this issue could also happen with other intents/utterances and, at the moment, we don't have any solutions the handle this.
