### ISSUE TITLE
LUIS Bing Spell Checker Stopped Working

### ISSUE THREAD

**Issue by jagadishg** [Microsoft/Cognitive-LUIS-Windows#67]
I have set both verbose and spellCheck flags to true. It doesn't make any difference.

`verbose=true&spellCheck=true`

It was working fine couple of weeks before (Mid of Oct 17). It just stopped working recently. 

I noticed that [Luis.ai ](url) page does not have "My Keys" section anymore. What happened to it?

Any help?

**Comment by TiMeJuMp** [comment]
It is also not possible to activate it in the constructor of the LuisClient class. 
Do you prefer a new overloading? 

public LuisClient(string appId, string appKey, bool verbose = true, string domain = "westus");
public LuisClient(string appId, string appKey, string baseApiUrl, bool verbose = true, string domain = "westus");
