### ISSUE TITLE
Cross-intent entity matching

### ISSUE THREAD

**Issue by pvanaarde** [Microsoft/Cognitive-LUIS-Windows#69]
Hi,

We have an issue where our LUIS model doesn't identify entities as expected. The problem is that even though the correct intent is recognized the entity identified is from an unrelated intent. The detailed scenario below...

We have an intent called **_ContactProfile_** with entities related to contact information, for example, name, email, surname, etc.
An utterance that we're testing with is '_can you get fred's contacts for me_'. In this utterance, we expect 'fred' to be identified as a _**ContactName**_. Instead, 'fred' is identified as a _**DocumentName**_ entity, which is only used on a completely different intent relating to Search functionality.

Additionally, I exported this LUIS app and imported it as a new app in the portal. Without making any changes I ran into the same problem, although this time another entity is identified in ReferenceId, which is used in another intent again.

Please advise.
Pieter

**Comment by DL-LiveTiles** [comment]
Any feedback on this?

**Comment by Bazorpazorps** [comment]
We're still having this issue some months on now.  Here are some example utterances using the same model months apart:

## Input
1. _"find fred smith's contact details"_
2. _"get fred's address book"_
3. _"can you get fred's contacts for me"_

## Expected LUIS Output
1. "find [$ContactName]'s contact details" (ContactProfile intent)
2. "get [$ContactName]'s address book" (ContactProfile intent)
3. "can you get [$ContactName]'s contacts for me" (ContactProfile intent)

## Actual LUIS Output
1. a) 2017-11-24 "find [$DocumentName]'s contact details" (ContactProfile intent)
   b) 2018-02-09 "find [$ContactName]'s contact details" (WebSearch intent)
2. a) 2017-11-24 "get [$ReferenceID]'s address book" (ContactProfile intent)
   b) 2018-02-09 "get [(no entity recognised)]'s address book" (BookMeeting intent)
3. a) 2017-11-24 "can you get [$DocumentName]'s contacts for me" (ContactProfile intent)
   b) 2018-02-09 "can you get [(no entity recognised)]'s contacts for me" (ContactProfile intent)
