### ISSUE TITLE
IntentHandler doesnot work for asp.net MVC

### ISSUE THREAD

**Issue by sunilpottumuttu** [Microsoft/Cognitive-LUIS-Windows#7]
The IntentHandler does not work in asp.net MVC application. The code will deadlock
For all the async operations add ConfigureAwait(false); Please see the below URL
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by heshamelbaz** [comment]
@ahmkel please resolve that

**Comment by Ahmkel** [comment]
Fixed on latest commit
