### ISSUE TITLE
LUIS API—Free says 10,000 transactions free per month but after 1,000 calls only the quota is exceeded

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [Microsoft/Cognitive-LUIS-Windows#73]
In the LUIS pricing page given [here](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/language-understanding-intelligent-services/) it says,

LUIS API—Free 10,000 transactions free per month

but I receive an email saying that I am about to approach my quota limit and the limit is 1,000 API calls and this isn't the first time it happened, could you please tell why is it so and why isn't it as mentioned on the LUIS web page, could you please clarify or is there something I am missing?

![image](https://user-images.githubusercontent.com/17563774/34778653-f240df4c-f643-11e7-8bc4-a07077739d99.png)

**Comment by jgarciadeltoro** [comment]
Happened to me as well...

**Comment by v-geberr** [comment]
Please make sure you are using your programmatic key, in the LUIS website, for authoring calls onlyt and that all endpoint calls are made using a LUIS subscription key. There is a free F0, and a paid, S0, tier. https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-boundaries#key-limits

**Comment by kendomen** [comment]
I had to update to the subscriptionKey using this command:

msbot update luis --appId <appId> --subscriptionKey <subscriptionKey> --secret “<botSecret>“
