### ISSUE TITLE
Not able to Add key for NorthEurope Region in my LUIS App

### ISSUE THREAD

**Issue by tinuCoder** [Microsoft/Cognitive-LUIS-Windows#80]
Hi,

I have my Bot service deployed in North Europe region and i also created a luis app on portal.azure for NorthEurope location. While i log into LUIS.ai site with the same credentials i am unable to add my tenant keys. PFB screenshots

![image](https://user-images.githubusercontent.com/25457761/37585027-18c65c52-2b71-11e8-9b54-3b7f2d19089a.png)

![image](https://user-images.githubusercontent.com/25457761/37585051-28a33a50-2b71-11e8-96c9-807ccf06d8fd.png)

![image](https://user-images.githubusercontent.com/25457761/37585152-8b0c7c38-2b71-11e8-8f38-dc15b9a0e576.png)

**Comment by v-geberr** [comment]
Use https://eu.luis.ai/ for authoring and publishing in Europe.

**Comment by tinuCoder** [comment]
Hey @v-geberr thanks alot for this. 

I totally forgot about the domain and ....

Well but thanks to you.
