### ISSUE TITLE
How do I extend the max utterance of each intent

### ISSUE THREAD

**Issue by CalvinFengDatacom** [Microsoft/Cognitive-LUIS-Windows#84]
Hi, I would like to know what is the maximum number of utterance for an intent. And is there a way to upgrade the number of utterance? Should I upgrade my service?

**Comment by stevkan** [comment]
Hi @CalvinFengDatacom,

You can refer to this [doc ](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries)that details the LUIS boudaries.

**Comment by CalvinFengDatacom** [comment]
@stevkan Thanks, I can see there are maximum 15,000 utterances per application, but is there a limitation of how many maximum the utterance could be in one intent?

**Comment by stevkan** [comment]
@CalvinFengDatacom,

The max appears to be about 1000 per intent. However, as suggested [here](https://stackoverflow.com/questions/41282430/ms-luis-ai-maximum-number-of-utterances-per-intent-app), you might want to consider the need for a high number of utterances and if there is a way to streamline the overall process (see the comments to the provided answer).

**Comment by CalvinFengDatacom** [comment]
@stevkan Cool, thanks. We can discuss the solution base on these comments. I will close this bug soon.
