### ISSUE TITLE
Dynamically create dialogues

### ISSUE THREAD

**Issue by fplaten** [Microsoft/Cognitive-LUIS-Windows#85]
Hey guys,

I'm using the LUIS SDK to create dialogs for a chatbot and everything is working fine so far.

I now thought about creating form dialogues dynamically from json, but as far as I unterstood, I'll always need to rebuild the application? Additionally I need to create some references in code (the actual class referencing the dialog.json and a method to call that class).

Are those assumptions right and will there be a way to add new forms dynamically in the future? I'm currently create QnA pairs for the QnA Maker from the outside and would love to use a comparable functionality with LUIS.

Best regards,
Florian

**Comment by stevkan** [comment]
@fplaten, are you still needing help on this issue or were you able to get it resolved?

**Comment by stevkan** [comment]
Closing due to lack of response.
