### ISSUE TITLE
Bing spell checker in my LUIS makes it in wrong way

### ISSUE THREAD

**Issue by singhsurya** [Microsoft/Cognitive-LUIS-Windows#86]
Hi there,

I am using LUIS with bing spell checker. When I provide a sentence "Where to find it", the bing spell checker updates it to "wheretoget.it". I don't see any way to overcome this. I don't want to train this sentence to my intent as it doesn't mean anything in my context. Do you have any idea to resolve this problem?

**Comment by stevkan** [comment]
@singhsurya, please post this question on the Bing Spell Check API Uservoice channel, located [here](https://cognitive.uservoice.com/forums/598195-bing-spell-check).

Closing as it is not an issue with LUIS.
