### ISSUE TITLE
Can LUIS handle '#'?

### ISSUE THREAD

**Issue by zanechua** [Microsoft/Cognitive-LUIS-Windows#88]
Trying to see if LUIS can handle the special character '#' but it doesn't even seem to be showing up in the LUIS endpoint utterances

**Comment by stevkan** [comment]
@zanechua, the "#" (hash) character is typically read as an anchor element in the path of a URL. As such, you need to escape the hash as "%23" for LUIS to read it as the special character. For example, 

https://{region}.api.cognitive.microsoft.com/luis/v2.0/apps/{appId}?subscription-key={subscriptionKey}&timezoneOffset=-360&q=%23vegas having a lot of fun

resolves to

https://{region}.api.cognitive.microsoft.com/luis/v2.0/apps/{appId}?subscription-key={subscriptionKey}&timezoneOffset=-360&q=%23vegas%20having%20a%20lot%20of%20fun

resulting in the following:
![image](https://user-images.githubusercontent.com/18403946/49489624-d3172d00-f800-11e8-9df3-ed371b339978.png)

In this case, I'm using a pattern set as:
![image](https://user-images.githubusercontent.com/18403946/49489665-08237f80-f801-11e8-9da4-3b2358d098bc.png)

**Comment by zanechua** [comment]
Ah. Thanks! I guess it makes sense to use the encoded version of it.

Yeah. That's my intended use case as well
